sudo: required
services:
  - docker

before_install:
  - docker build -t sbkumaran/docker-react -f DockerFile.dev .
# this command with run on the docker container and exit with results
script:
  - docker run -e CI=run sbkumaran/docker-react npm run test -- --coverage